# -*- coding: utf-8 -*-
"""
Created on Mon May 28 16:33:11 2018

Each new term in the Fibonacci sequence is generated by adding the previous two
 terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

@author: pallo
"""
# function to create fibonacci sequence. # values through append

def fib(n):                                                                                                 
    fib = [0, 1, 1]                                                                                           
    for f in range(2, n):                                                                                      
        fib.append(fib[-1] + fib[-2])                                                                         
    return fib[n]


# Runs though the fibonacci numbers and adds the even fibonacci numbers to
# the array evenfibs.
evenfibs=[]
i=1
while fib(i)<4000000:
    i=i+1
    if fib(i)%2==0:
        evenfibs.append(fib(i))
print(sum(evenfibs))